version: 2

models:

    - name: sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: identifier of the orders
            tests : 
            - not_null 

          - name: products_id
            description: identifier of the products
            tests : 
            - not_null 

          - name: qty

          - name: turnover
            description:  amount received in sales for a stated period
            tests : 
            - not_null 

          - name: purchase_cost
            description: total cost for the acquisition of goods and services from external sources
            tests : 
            - not_null 

          - name: margin
            description: difference between net sales and the cost 